// #KEYWORDS:- (SELF INVOKING FUNCTION)

// HERE WE ARE NOT CALLING THE SELF INVOKING FUNCTION. IT WILL AUTOMATICALLY GETS 
// EXECUTED ONCE WITHOUT BEING CALLED AND ALL THE VAR AND THE FUNCTION WILL DIE
// AND WE CANT REFERNCE THEM AGAIN IN THE PROGRAM. THESE ARE BASICS OF CLOSURES.
var add=(function(a,b) {
    var counter=10;
    console.log('a+b:-'+(counter+a+b));
}(5,3));


console.log('ACCESSING THE VARIABLES BELOW OF SELF INVOKING FUNCTION WILL FAIL');
try {
    console.log('ACCESSING THE SELF INVOKING FUNCTION AGAIN NOW:-'+add(10,4));
    console.log('counter:-' + counter);
} catch(err) {
    console.log('NOT ABLE TO INVOKE THE SELF INVOKING FUNCTION NOR WE CAN \
    ACCESS ITS VARIABLES:-'+err);
}
